# Generated by Django 6.0 on 2025-12-11 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cart_app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cart",
            old_name="updated_at",
            new_name="created_at",
        ),
    ]
